
replicas: 2
databaseName: userdb
container:
  port: 5432

service:
  protocol: TCP
  port: 5432
  targetPort: 5432
  nodePort: 0
  type: ClusterIP

serviceAccount:
  create: true
  name: pgset-sa
  namespace: default


user: testuser
password: password
masterUser: master
masterPassword: password
rootpassword: password

image:
  name: crunchydata/crunchy-postgres
  tag: centos7-9.6.6-1.7.0
  pullPolicy: IfNotPresent

resources: {}
#  requests:
#    cpu: 100m
#    memory: 256Mi
#  limits:
#    cpu: 500m
#    memory: 512Mi

persistentVolume:
  enabled: true
  storageClass: basic
  accessModes: 
    - ReadWriteOnce
  size: 3Gi
  annotations: {}
